### ISSUE TITLE
"Global" options aren't being parsed

### ISSUE THREAD

**Issue by contentfree** [leejarvis/slop#115]
Given:

```
opts = Slop.parse do
  on :a=, 'Option A'

  command :sub do
    on :b=, 'Option B'
  end
end

puts opts.to_hash(true)
```

`ruby test.rb sub -a 1 -b 2` results in `{:a=>nil, :sub=>{:b=>"2"}}`. My expectation was: `{:a=>"1", :sub=>{:b=>"2"}}`

I'm using 3.4.5. What am I doing wrong?

**Comment by leejarvis** [comment]
Sorry, but I'm closing this. I don't actively work on v3 and v4 doesn't have support for commands. If there's enough desire, I would create slop-commands or even built it into v4. However, as is evident from experience, it's seldom used and hard to be generic. Also excluding it helps keep Slop simple.
