### ISSUE TITLE
Breaks rubygems on ruby 1.9.3

### ISSUE THREAD

**Issue by next-mad-hatter** [leejarvis/slop#158]
On ruby 1.9.3, installing v.3 results in non-updateable gems set, since v.4 still advertises itself as an update to v.3, but fails at runtime.

If the logic is not implementable via standard rubygems mechanisms, maybe it'd be better to make v.4 a distinct gem?

**Comment by leejarvis** [comment]
You need to tell Rubygems that you want version `~> 3.0` of Slop in your project. That way you won't get the incompatible version.

**Comment by next-mad-hatter** [comment]
If I am not mistaken, there is no way to do that for a vanilla rubygems install -- now is there?

**Comment by leejarvis** [comment]
If you're building a library, you can specify the version in your `gemspec`, if you're just wanting to use a specific version in a script you're running, you can do this:

```ruby
gem 'slop', '~> 3.0'
require 'slop'

p Slop::VERSION
```

**Comment by next-mad-hatter** [comment]
That's not what I mean (I think the above snippet doesn't even touch the gems) -- the point is that if I do, say,
```
    $ gem install ruby-lint pry
```
(where both install Slop as a dependency), every `gem update` after that will fail (as rubygems does not do anything akin to apt-style-pinning -- again, if I am not mistaken), rendering the installed gem set non-updatable.

**Comment by leejarvis** [comment]
I still don't follow. Using those steps you suggested do not cause any failures or errors for me. Both ruby-lint and pry use version 3 of Slop. Running gem update on 1.9 shouldn't update Slop to version 4 because we've [specified that it's non-compatible](https://github.com/leejarvis/slop/blob/master/slop.gemspec#L16). if it does, that's not Slops fault. It's common to upgrade gems and specify a minimum Ruby version

**Comment by next-mad-hatter** [comment]
> that's not Slops fault

It really does seem now a rubygems shortcoming [1] -- I had not encountered this before.  Anyway, thanks for pointing me to the spec index direction.

> Running gem update on 1.9 shouldn't update Slop to version 4

Ah but it will try -- and fail :)

```
# gem environment | grep VERSION
  - RUBYGEMS VERSION: 2.4.5
  - RUBY VERSION: 1.9.3 (2013-11-22 patchlevel 484) [x86_64-linux]
# gem install slop
ERROR:  Error installing slop:
	    slop requires Ruby version >= 2.0.0.
```

Closing issue now since this is how rubygems operates.

[1] https://github.com/rubygems/rubygems/issues/798
