### ISSUE TITLE
jRuby compatibility with Slop 4.0.0

### ISSUE THREAD

**Issue by jcoyne** [leejarvis/slop#160]
The ruby version spec >= 2.0.0 set in the gemspec makes the gem incompatible with jRuby (jruby 1.7 only supports the 1.9.3 language spec). Are there any ruby 2.0.0 specific features you are using?  Would you consider adding jruby as a supported version?  

This is a particularly gnarly issue because bundler does not take the required ruby version into effect when creating a dependency graph. Thus I need to specify "gem 'slop', '< 4.0.0'"  if I want to use jRuby.

**Comment by leejarvis** [comment]
Yeah I'm using lots of Ruby 2.x features (I think). I think it's mostly kwargs. The big 4.0 push was always intended to only support Ruby 2.x and above. 

Presumably this means Slop would only be compatible with JRuby version 9000?

FWIW I'm happy to continue supporting older Ruby versions with the 3.x branch of Slop.
