### ISSUE TITLE
Feature: Show defaults in usage (help) text

### ISSUE THREAD

**Issue by MadBomber** [leejarvis/slop#164]
I like to show the defaults when they exist with the usage help text.  Doesn't look like Slop shares my philosophy.

**Comment by leejarvis** [comment]
It's not really about sharing philosophy. There are so many ways you can format your help text, that I  choose to do the simplest thing. I could have added defaults, but then people might want them formatted differently, or want them removed altogether.

It's pretty easy to add them, though. Here's how you can do it for string options only:

```ruby
module Slop
  class StringOption
    def to_s(offset: 0)
      "%-#{offset}s=%s  %s" % [flag, default_value, desc]
    end
  end
end

opts = Slop.parse do |o|
  o.string "--name", default: 'admin'
  o.string "--thing", "some thing"
end

puts opts
```

```
usage: run.rb [options]
    --name=admin
    --thing=  some thing
```

I'd be up for adding a `display_default` or similar option to `Option#to_s` but I think that'll just prompt more questions.

**Comment by MadBomber** [comment]
Thanks Lee.  I just pushed a new gem, cli_helper, that encapsulates the way I have been using some boilerplate code on my quick and dirty CLI-based utilities.  I will take you example and incorporate the way that I like to see the defaults displayed within this new gem.

Dewayne
  o-*
