### ISSUE TITLE
Mandatory argument missing not throwing MissingArgument error

### ISSUE THREAD

**Issue by abgalphabet** [leejarvis/slop#178]
I am new to Ruby and tried to follow the example for CLI options parsing. i have written below however it doesn't throw any error? 

I am using Slop v4.2.0 with Ruby 2.0.0
I would expect it would throw MissingArgument before reaching Zip::File.open() line.

require 'slop'
require 'zip'

options = Slop.parse do |o|
	o.string '-s', '--sdk', 'the sdk symbolic name/link'
	o.string '-f', '--file', 'the archive file'
	o.string '-d', '--dest', 'the unzipped archive dest', default: Dir.pwd
end

Zip::File.open(options[:file]) do |zip_file|
	zip_file.each do |entry|
		puts 'Extracting #{entry}'
		entry.extract('#{options[:dest]}/#{entry.name}')
	end 
end

File.symlink(File.join(options[:dest], File.basename(options[:file], '.*')), File.join(options[:dest], options[:sdk]))

**Comment by leejarvis** [comment]
This error is thrown when the option is used, but no argument is passed to it. For example, it would raise this error if you provided `--file` as a command line argument.

This means you need to check that the option was passed at all. For this you can check `file?` for example. Alternatively you could just check if `ARGV` includes any of the options:

```ruby
unless options.file? && options.dest?
  abort "Must provide mandatary options --file and --dest"
end
```

I'm not against enforcing the existents of options in Slop but that feature is not yet present. I'm open to suggestions for how one might expect this to be implemented.

**Comment by abgalphabet** [comment]
I think it ll be a quite useful features over others if there is such "mandatory" argument builtin rather than having to check ourselves with the code block
```
unless options.file? && options.dest?
  abort "Must provide mandatary options --file and --dest"
end
````

I have used ostruct + optparse doing the same but i found it too tedious comparing to Slop.
IMHO, If there is config option to raise missing mandatory options/arguments error when parsing, it will be hassle-free and make Slop stand out among other gems doing the same CLI domain.

**Comment by leejarvis** [comment]
What about something like this?

```ruby
Slop.parse do |o|
  o.string '-f', '--file', required: true
end
```

Then Slop could check and raise `RequiredOptionMissing` if the option is not present. Not keen on `mandatory` or `compulsory` as key names, really.

**Comment by abgalphabet** [comment]
+1. `required` config and `RequiredOptionMissing` is definitely much better than `mandatory` or `compulsory`

**Comment by leejarvis** [comment]
After some thought I'm not convinced it should be the job of the option parser to identify compulsory options. I feel like that feature in general is not a good UX and that whilst arguments might be compulsory, options generally shouldn't be; or at least if they are there are more conditions than "this option is required 100% of the time"
