### ISSUE TITLE
negative number being parsed as an option

### ISSUE THREAD

**Issue by jdh-invicara** [leejarvis/slop#179]
Code:

    opts = Slop::Options.new
    opts.int '-dx', '--delta_x', 'add to all x values'
    options = Slop::Parser.new(opts).parse(ARGV)

Command line:

    ./myscript.rb -dx 1   -- works as expected
    ./myscript.rb -dx -1  -- throws "unknown option `-1' (Slop::UnknownOption)"

**Comment by leejarvis** [comment]
Thanks for reporting this. I had the same issue in v3 so I'll have to see how it was dealt with. Keeping in mind that a number as an option name is completely valid. At the moment option data is not shared so for example one option cannot identify if the previous option consumed an argument that looks like an option but probably isn't. We also don't do lookaheads at parse time so this might be tricky
