### ISSUE TITLE
Inconsistent inaccurate README for version 3

### ISSUE THREAD

**Issue by Zloy** [leejarvis/slop#183]
This code produces the error **undefined method `on' for #<CommandlineOptions:0x00000002479300> (NoMethodError)**

  ```
 require 'slop'
 class CommandlineOptions
   def initialize
     @options = Slop.parse do
       on 'i', '--iface=', 'Interface to listen, default 0.0.0.0', as: String
       on 'p', '--port=', 'Port to listen, default 3000', as: String
     end
   end
    
   def to_h
     @options.to_h
   end
 end
```

**Comment by leejarvis** [comment]
Your code is running against version 4 of Slop, not version 3. Your code works perfectly fine on V3:

```ruby
 gem 'slop', '< 4'
 require 'slop'

 class CommandlineOptions
   def initialize
     @options = Slop.parse do
       on 'i', '--iface=', 'Interface to listen, default 0.0.0.0', as: String
       on 'p', '--port=', 'Port to listen, default 3000', as: String
     end
   end

   def to_h
     @options.to_h
   end
 end

 CommandlineOptions.new
```

**Comment by Zloy** [comment]
yes, you're right

**Comment by leejarvis** [comment]
FWIW if you have access to Slop v4, I would recommend using that rather than version 3.

**Comment by Zloy** [comment]
Unfortunally I've locked to slop 3.6 due to pry dependency 

Bundler could not find compatible versions for gem "slop":
  In Gemfile:
    pry (< 0.11.0, >= 0.9.10) ruby depends on
      slop (~> 3.3.1) ruby

    slop (4.0.0)
