### ISSUE TITLE
Argument after "--" is ignored if it happens to be the same as an option that's before "--"

### ISSUE THREAD

**Issue by dg1727** [leejarvis/slop#194]
First, thanks for writing Slop!  I think I've found an issue with Slop 4.3.0 using the following file:  

[sloptest.txt](https://github.com/leejarvis/slop/files/329000/sloptest.txt)

I renamed the file from .rb to .txt for GitHub upload.  

First, a test case that works as expected:  
**`$ sloptest.rb data -- moreData --blah --notAnOption`**
`Blah:  false`
`Unrecognized params:  ["data", "moreData", "--blah", "--notAnOption"]`

If I then add --blah before the "--":  
**`$ sloptest.rb data --blah -- moreData --blah --notAnOption`**
`Blah:  true`
`Unrecognized params:  ["data", "moreData", "--notAnOption"]`

Now --blah has disappeared from `opts.arguments`.  

What I would prefer to see in this 2nd case is:  
**`$ sloptest.rb data --blah -- moreData --blah --notAnOption`**
`Blah:  true`
`Unrecognized params:  ["data", "moreData", "--blah", "--notAnOption"]`

**Comment by dg1727** [comment]
The "--blah" isn't consuming the --, because --blah is declared as a bool, so it doesn't take any arguments.  In addition, if I move --blah to be before the argument "data", the issue is still the same:  (--blah, even though it appears after the --, is missing from the output of the opts.arguments method)

**`$ sloptest.rb --blah data -- moreData --blah --notAnOption`**
`Blah: true`
`Unrecognized params: ["data", "moreData", "--notAnOption"]`

**Comment by leejarvis** [comment]
Sorry this took so long to fix. To be honest it just completely slipped my mind. Should be good now, and I'll release a new bug fix version. Thanks for reporting! 💜
