### ISSUE TITLE
Feature:  Distinguish arguments before vs. after "--"

### ISSUE THREAD

**Issue by dg1727** [leejarvis/slop#195]
I suggest adding a couple of outputs to Slop which are the same as the existing `.arguments`, but separated into those before and after any "--".  Names might be something like `bad_options` and `forced_args` respectively.  

Motivation:  

I'm using Slop to write a Ruby script which is a wrapper around a 3rd-party binary.  My script imitates some of the option parsing of that binary, and acts on some of the options while passing some of the options to the binary.  My script is maintained & distributed independently of that binary, so should detect (i.e., issue an error message in response to) any options that were unknown when I wrote the script (options that are meant for a future version of the binary).  

My script is looking for an optional argument which is unrecognized by Slop and doesn't belong to any single- or double-dash option.  The binary expects this kind of argument, and I want to intercept this argument in my script.  

The difficult case is if this argument starts with a "-".  The argument could be a forced argument (after a standalone "--"), or it could be an option for a future version of the binary (or it could be a spelling mistake for a current-version option - I would treat this like a future-version option).  

In order to tell which, I would have to know whether the unrecognized "-whatever" was before or after a "--".  But I can't just look in ARGV for --, because the -- might be consumed by a preceding dash option that can take the string "--" as an argument and that allows whitespace (as opposed to "=") between the option & argument.  (I'm thinking about general uses of Slop, not just for the binary I'm working with.)  

To make up an example:  Suppose there is a "filemode" option that can take "--" as an argument:  

`command --filemode -- --option`

In this case, --option is an option name, not an argument, because the "--" was consumed by "--filemode."  So if Slop tells my script that the unrecognized argument is --option, & my script detects that this is after a --, it appears in my script that --option is the forced argument that my script is looking for, but in fact --option is a future-version option.  

If --option appeared in a `.bad_options` array, then my script would detect easily that --option was a future-version option rather than a forced argument.  I'm asking for `.forced_args` also because it might help someone someday, and I hope it will be easy to add at the same time as `.bad_options`.  

My current workaround is:  If there is only one unrecognized argument, and it starts with a -, then issue an error message prompting the user to run the binary directly.  But I still think the suggested feature would be worth adding to Slop, and should be much easier to do there than in code that relies on Slop.

**Comment by dg1727** [comment]
The name `.bad_options` isn't quite right, because there could be strings in that array that aren't meant or detected as options, i.e., they don't start with a dash.  Maybe something like `.pre_doubledash_args`.

**Comment by leejarvis** [comment]
Sorry I'm a bit lost at what you're suggesting. I think talking in code would be preferable. I think what you're saying is that this:

```ruby
opts = Slop::Options.new do |o|
  o.string "--filename"
end

items  = %w(--filename -- --option)
result = opts.parse(items)

p result
```

Which currently blows up because `--option` isn't an option name, should actually recognise `--` is separating arguments and should *not* be consumed as an argument to `--filename`

Is that correct?

I don't like the idea of adding different variations of `args` or `options`. We already have `result.used_options` and `result.unused_options`. For more granular operations developers would be expected to use these methods on conjunction with `ARGV` for their own use-case.
