### ISSUE TITLE
option style `-p5` vs `-p 5`

### ISSUE THREAD

**Issue by rickhull** [leejarvis/slop#199]
`test.rb`
```ruby
require 'slop'

opts = Slop.parse do |o|
  o.integer '-p'
end

p opts[:p]
```

testing...
```shell
rwh@dadtop:~/test$ ruby test.rb -p 5
5
rwh@dadtop:~/test$ ruby test.rb -p5
/home/rwh/.gem/ruby/2.4.0/gems/slop-4.4.1/lib/slop/option.rb:54:in `ensure_call': missing argument for -p (Slop::MissingArgument)
	from /home/rwh/.gem/ruby/2.4.0/gems/slop-4.4.1/lib/slop/parser.rb:103:in `process'
	from /home/rwh/.gem/ruby/2.4.0/gems/slop-4.4.1/lib/slop/parser.rb:110:in `try_process'
# ...
```

**Comment by rickhull** [comment]
That's some pretty ugly behavior to subject a user (and I don't mean the program author who chose slop) to, for a relatively standard option specification.

**Comment by rickhull** [comment]
You may want to keep an eye on this: https://github.com/rickhull/healthy_options

See the tests in particular.

Maybe we can collaborate on slop v5?  I don't think I can or want to build out healthy_options as a full-blown competitor.  Just looking at this problem from a command line perspective.

**Comment by leejarvis** [comment]
Thanks for reporting. The issue here is the ambiguity. Slop v3 had a config option which switched the behaviour between treating `-abc` as `-a` with the argument `bc` as you suggest, vs `-a` `-b` `-c`. The former of which I think is very popular.

I don't think the ambiguity can be solved without a configuration option. The best we could do is check if all `-a` `-b` and `-c` options exist and are all boolean options, otherwise fall back to `-a` passing the argument `bc`. I think that's really sloppy, though.

**Comment by rickhull** [comment]
See the tests for healthy_options.  It's possible to disambiguate `-abc` depending on how the options are defined.  Do you see a future where slop v4 or v5 could pass the healthy_options tests?  My code in lib/ passes the tests.  I'd like to see an option lib that passes the healthy_options tests and behaves like slop.

Do you have any interest in integrating this work into slop?  I realize that these two angles might just be fundamentally incompatible.

**Comment by leejarvis** [comment]
@rickhull Thanks, let me know what you think about the above fix. Feel free to run against your test suite (unfortunately I won't have time to properly plug Slop in for a while). Happy to work with you on improving Slop. I consider this a regression so I'll deploy this as a bug fix soon.

**Comment by rickhull** [comment]
Sure thing.  After our conversation on IRC, I am basically giving up on healthy_options and I think Slop v4 can support at least 90% of what I have in mind, if not 100%.  I'll direct my efforts to applying my cases to Slop.  Cheers
