### ISSUE TITLE
What about a filename that is always required?

### ISSUE THREAD

**Issue by pitosalas** [leejarvis/slop#205]
e.g.

> myutil foo.bar -v -f

How would I represent that?

**Comment by leejarvis** [comment]
Hi Pito. Which part is required? The `foo.bar`? And what do the `-v` and `-f` represent in your example? Does the `-f` force the requirement or is it always required? 

I think you probably want something like this:

```ruby
require "slop"

opts = Slop.parse do |o|
  o.bool "-v"
  o.bool "-f"
end

file = opts.arguments.first

unless file
  raise ArgumentError, "must provide a file"
end

p [file, opts.to_h]
```

```
ruby example.rb foo.bar -v -f
["foo.bar", {:v=>true, :f=>true}]
```

**Comment by pitosalas** [comment]
Thanks for the response, Lee, that’s awesome :) So simple!

One follow up, and what if there was a second, optional filename, e.g.

myapp required.file [ optional.file ] [ -f ] [ -v ]

?

Pito Salas
Brandeis Computer Science
Feldberg 131

**Comment by leejarvis** [comment]
No problem.

`opts.arguments` is just a normal Array, so you can check for values at their index and decide whether or not to enforce their presence.

e.g:

```ruby
file = opts.arguments.first

unless file
  raise ArgumentError, "must provide a file"
end

optional_file = opts.arguments[1]
optional_file ||= "default_value"

# ...
```

Hope that helps. Closing this issue but feel free to ask questions.
