### ISSUE TITLE
regexp option does not work when using ^ 

### ISSUE THREAD

**Issue by bessakhi** [leejarvis/slop#212]
my script (parser.rb)
require 'slop'

opts = Slop.parse do |o|
  o.regexp '-r','--regex', 'regex expression'
end
str = "aa=1\nab=1\na=2"
p str.match(opts[:regex])

example:
my command is as follows:
ruby parser.rb --regex '^a=.*'  --> a=1
ruby parser.rb --regex '^^a=.*'  --> a=2

i have to write '^' twice in order to work correctly.
please any idea?

Best regards - BES

**Comment by leejarvis** [comment]
What version of Slop are you using? This works as expected for me:

```ruby
require "slop"

opts = Slop.parse %w(--regex ^a=.) do |o|
  o.regexp '-r','--regex', 'regex expression'
end

str = "aa=1\nab=1\na=2"

p str.match(opts[:regex]) #=> #<MatchData "a=2">
```

**Comment by bessakhi** [comment]
Hi 
I'm using 4.5.0 version.
I confirm that your example, works for me too.

I'm giving you another example:
On windows, I use Cmder as console.

This is the file:

#parser.rb file
require 'slop'
opts = Slop.parse do |o|
  o.regexp '-r','--regex', 'regex expression'
end
str = "aa=1\naa=2\nab=3\na=4\na=5"
p str.scan(opts[:regex])         #["a=1", "a=2", "a=4", "a=5"] we have a problem here.
p str.scan(/^a=./)                  #["a=4", "a=5"]  it works
p str.match(opts[:regex])       #<MatchData "a=1">
p str.match(/^a=./)               #<MatchData "a=4">

all slop matching are not correct.

Question
what's the difference between the method (A):
opts = Slop.parse %w(--regex ^a=.) do |o|
  o.regexp '-r','--regex', 'regex expression'
end

and this method(B):
opts = Slop.parse do |o|
  o.regexp '-r','--regex', 'regex expression'
end

The method (A) works fine, but I can not use it because I have other parameters to declare.
Thanks so match.
Essakhi

**Comment by leejarvis** [comment]
Method A is just passing an array instead of ARGV (which is passed by default in method B). So it looks like this is due to some sort of shell escape method that's happening in your console application. Could you try another app to see if there's any difference?

**Comment by leejarvis** [comment]
Closing until there's more info.
