### ISSUE TITLE
print help for positional argument(s)

### ISSUE THREAD

**Issue by gnowxilef** [leejarvis/slop#215]
is there a way for the parser to print a help message for positional arguments?

e.g.
```ruby
usage: foo [options] positional
  -f, --foo foo
  -b, --bar bar
```

while slop supports positional args, it doesn't support printing it out in the usage i believe.
related to #202

**Comment by leejarvis** [comment]
You'll have to add this to the `banner` manually. Here's an example:

```ruby
require "slop"

opts = Slop.parse do |o|
  o.banner = "usage: foo [options] arg1 arg2"

  o.string "f", "-foo", "foo"
  o.string "b", "-bar", "bar"
end

puts opts

# usage: foo [options] arg1 arg2
#    f, -foo  foo
#    b, -bar  bar
```
