### ISSUE TITLE
Regexp error in Slop.string_to_option(s)

### ISSUE THREAD

**Issue by rinkevichjm** [leejarvis/slop#217]
the correct method should have this Regular Expression, please use Rebular to check your Regexps at <http://rubular.com/>.
Thank you. 
def self.string_to_option(s)
    s.gsub(/[?\\:^|_]?([a-z]+)/) { $1.capitalize} +"Option"
end

**Comment by olleolleolle** [comment]
Thanks for looking at this!

Can you give an input example which fails on the old way and works with the new? (Aka a unit test.)

**Comment by leejarvis** [comment]
Yeah this seems fine to me at the moment, so closing until there's an example
