### ISSUE TITLE
Suppression Fidelity

### ISSUE THREAD

**Issue by voltechs** [leejarvis/slop#219]
I suggest allowing the ability to suppress errors specifically.

I'd like to be able to only suppress `Slop::UnknownOption`; the other errors are still helpful to me.

**Comment by leejarvis** [comment]
Thanks for the suggestion. I guess I'd be up for allowing `supress_errors` to take an array of exception classes that will be suppressed, though I do question whether this is really a good way to direct users over preferring their own `begin/rescue` block.

**Comment by leejarvis** [comment]
This is non-trivial and it's a bit of an edge case I think. If anyone is interested in working on this though then I'd be happy to consider a proposal. I'm closing this for now, though.
