### ISSUE TITLE
Duplicate Options should be a warning

### ISSUE THREAD

**Issue by voltechs** [leejarvis/slop#220]
I don't see a reason not to simply overwrite previous options with the most recent.

https://github.com/leejarvis/slop/blob/f560342a90e923a1001861819b03c4572c2563a9/lib/slop/options.rb#L134

Should be a warning, not an exception that grinds the entire operation to a halt.

**Comment by leejarvis** [comment]
@voltechs Fair point, but conversely I don't see any reason not to tell the user when they're doing something odd/unsupported. Not grinding to a halt seems reasonable, though, so I'm up for changing this.

**Comment by leejarvis** [comment]
Closing this. Happy to re-open if it gets more votes, but I don't think it's a big enough issue to warrant time at the moment.
