### ISSUE TITLE
trying to print help but required option won't let me

### ISSUE THREAD

**Issue by jdawgaz** [leejarvis/slop#224]
did the first example, that had this option in it:

o.string '-l', '--login', required: true

then did a puts opts as per the documentation.

when trying to print the resulting help, I get a traceback: 'missing required option'

**Comment by leejarvis** [comment]
Thanks for reporting. This was added recently in #218. I guess we should allow required options to be missing when there's *no* options, e.g. so that help displays. That said, perhaps it's not necessary and consumers should rescue and print help. Any thoughts @woodruffw?

**Comment by woodruffw** [comment]
Hmm, I hadn't thought of this use case 😄 

What I'm doing in my programs is something like this:

```ruby
require "slop"

opts = Slop.parse do |o|
  o.string '-l', '--login', required: true
  o.on "-h", "--help" do
    puts o
    exit
  end
end
```

which results in this:

```
$ ruby foo.rb 
/home/william/.gem/ruby/2.4.0/gems/slop-4.6.0/lib/slop/parser.rb:87:in `block in parse': missing required option `-l', `--login' (Slop::MissingRequiredOption)

$ ruby foo.rb --help
usage: slop.rb [options]
    -l, --login  
    -h, --help 
```

IMO, this behavior makes sense -- invoking the program with `--help` explicitly ends the program early, whereas allowing `Slop.parse` to complete means accepting that it may throw various exceptions  (including `UnknownOption`):

```
$ ruby foo.rb --login foo --bar
/home/william/.gem/ruby/2.4.0/gems/slop-4.6.0/lib/slop/parser.rb:125:in `try_process': unknown option `--bar' (Slop::UnknownOption)
```

Based on the above, I think consumers should do their own rescuing here (or not use required options if they have enough edge cases to warrant that).

**Comment by jdawgaz** [comment]
require "slop"

opts = Slop.parse do |o|
  o.string '-l', '--login', required: true
  o.on "-h", "--help" do
    puts o
    exit
  endend


the above works for me. I would change this "bug" as a needed
documentation change, to do this instead of the puts opts, that is
there now.




--
Extra Ham Operator: K7AZJ
Registered Linux User: 275424
Raspberry Pi and Openscad developer


*The most exciting phrase to hear in science - the one that heralds new
discoveries - is not "Eureka!" but "That's funny...".*- Isaac. Asimov

**Comment by apohllo** [comment]
What about changing:

```ruby
begin
  opts = Slop.parse do |o|
    o.separator 'Check which definition questions does not have answers yet.'
    o.separator 'Options:'
    o.on '-h', '--help', 'print help' do puts o; exit; end
  end
rescue Slop::Error => ex
  puts ex
  exit
end
```

to

```
opts = Slop.parse do |o|
    o.separator 'Check which definition questions does not have answers yet.'
    o.separator 'Options:'
    o.on_error do puts o; exit; end
  end
```

Such a change would make the need for wrapping `Slop.parse` into rescue block unnecessary, which is a pro imho.

**Comment by leejarvis** [comment]
@apohllo Sorry for the delay I've been on holiday. Your proposal sounds OK to me. Do you fancy creating a PR? I think the Slop instance + optional exception class could be passed to the `on_error` callback too

**Comment by apohllo** [comment]
@leejarvis Thanks for the positive reponse :-) I'll try to have a look at that but I cannot promise anything.

**Comment by leejarvis** [comment]
I'm closing this, still happy to discuss the `on_error` change in that pull request, but I don't think this is a bug if the option is marked as `required`.
