### ISSUE TITLE
Slop fails to parse ARGV that starts with a =

### ISSUE THREAD

**Issue by YorickPeterse** [leejarvis/slop#226]
For a chat bot at GitLab we're using slop to parse the input so we can add support for various flags. One of our commands obtains the EXPLAIN output of a SQL query. The way we use this is like so:

    /command run explain SELECT COUNT(*) FROM todos WHERE state = 'pending'

We're currently using this particular syntax so you don't have to quote the query manually (which can be quite annoying). This eventually leads to Slop being invoked like so:

```ruby
require 'slop'

Slop.parse("SELECT COUNT(*) FROM todos WHERE state = 'pending'".split) # Here we emulate what ARGV would look like in the above case
```

This produces:

```
/home/yorickpeterse/.gem/ruby/2.4.1/gems/slop-4.6.1/lib/slop/parser.rb:119:in `try_process': undefined method `start_with?' for nil:NilClass (NoMethodError)
	from /home/yorickpeterse/.gem/ruby/2.4.1/gems/slop-4.6.1/lib/slop/parser.rb:60:in `block in parse'
	from /home/yorickpeterse/.gem/ruby/2.4.1/gems/slop-4.6.1/lib/slop/parser.rb:49:in `each'
	from /home/yorickpeterse/.gem/ruby/2.4.1/gems/slop-4.6.1/lib/slop/parser.rb:49:in `each_with_index'
	from /home/yorickpeterse/.gem/ruby/2.4.1/gems/slop-4.6.1/lib/slop/parser.rb:49:in `parse'
	from /home/yorickpeterse/.gem/ruby/2.4.1/gems/slop-4.6.1/lib/slop/options.rb:72:in `parse'
	from /home/yorickpeterse/.gem/ruby/2.4.1/gems/slop-4.6.1/lib/slop.rb:23:in `parse'
	from -e:1:in `<main>'
```

This seems to be cause by the `'='` values in the ARGV array.

I realise this is probably a bit of a weird case and we could probably require quoting the query, but I'm hoping there's a way of not having to do that (since escaping inner quotes gets really annoying).

**Comment by leejarvis** [comment]
Thanks Yorick. Can you test against the `pedantic-equals` branch linked to above? I agree this case is weird, but it's weirder that Slop blows up in the way it does.

**Comment by YorickPeterse** [comment]
@leejarvis This appears to work, producing the following:

```
$ ruby -Ilib -r slop -e "p Slop.parse('WHERE \'foo\' = 10'.split).arguments"
["WHERE", "'foo'", "=", "10"]
```

**Comment by leejarvis** [comment]
@YorickPeterse cut 4.6.2, you should be good to go.

**Comment by YorickPeterse** [comment]
@leejarvis Thanks! :+1: :tada:
