### ISSUE TITLE
Hash option type support

### ISSUE THREAD

**Issue by alexherbo2** [leejarvis/slop#234]
#### Command

```
{command} [-{option} {key} {value}]…
```

#### Ruby

```
{
  {option}: {
    {key}: {value}
  }
}
```

### Examples

With [Bulk] – a command-line tool to execute shell commands on arguments.

#### Command

``` sh
bulk \
  -command echo 'echo %{1} %{2}' \
  -command rename 'rename %{1} %{2}' \
  -command foo-bar 'foo-bar %{1} %{2}'
```

#### Ruby

``` ruby
{
  command: {
    'echo' => 'echo %{1} %{2}',
    'rename' => 'rename %{1} %{2}',
    'foo-bar' => 'foo-bar %{1} %{2}'
  }
}
```

[Bulk]: https://github.com/alexherbo2/bulk

**Comment by leejarvis** [comment]
Thanks for opening this issue. Could you please add more information about what you would like to see and exactly how the `Hash` option type would work? The previous version of Slop had a Hash option but the syntax is quite ambiguous so I don't think this is something that should be in the core library (particularly given that it's so easy to add yourself). I'm open to discussing it, though

**Comment by alexherbo2** [comment]
@leejarvis What was the previous syntax?

**Comment by leejarvis** [comment]
@alexherbo2 I couldn't find it, so maybe I was dreaming it. I thought it was something like this though:

```
run --hash "key:value,key,value"
```

At the moment your suggested syntax isn't really possible, that's because it's impossible to tell the difference between key values and "normal" command line parameters. You would likely have to hack something together

**Comment by alexherbo2** [comment]
Can’t we shift 2 times when encountering a [Hash] option?

[Hash]: https://ruby-doc.org/core/Hash.html

**Comment by leejarvis** [comment]
@alexherbo2 It's not really that simple but I can leave this open to investigate it properly at some point. If you fancy giving it a go then I'll be happy to help with some guidance.

**Comment by leejarvis** [comment]
Closing this as I won't get time to do it. Happy to help anyone who wants to work on it though!
