### ISSUE TITLE
Thor comparison

### ISSUE THREAD

**Issue by alexherbo2** [leejarvis/slop#235]
@leejarvis I’m new to [Slop].  How do you compare it with [Thor]?

[Slop]: https://github.com/leejarvis/slop
[Thor]: http://whatisthor.com

**Comment by leejarvis** [comment]
@alexherbo2 You can probably tell from just browsing the README files. Thor is an all-inclusive library for building complex command line applications. Slop is for simple and lightweight option parsing. It does not include support for commands and is much more comparable to the stdlib OptionParser

Hope that helps
