### ISSUE TITLE
`help: false` throws off separator position

### ISSUE THREAD

**Issue by ankane** [leejarvis/slop#253]
Hi, thanks for this great library! There seems to be an issue with the position of the separator when `help: false` is used on an earlier option.

```ruby
require "slop"

opts = Slop.parse do |o|
  o.boolean "--opt1", "opt1"
  o.boolean "--opt2", "opt2", help: false
  o.separator ""
  o.separator "Other options:"
  o.boolean "--opt3", "opt3"
  o.boolean "--opt4", "opt4"
end
puts opts
```

Expected

```txt
usage: repro.rb [options]
    --opt1  opt1

Other options:
    --opt3  opt3
    --opt4  opt4
```

Actual

```txt
usage: repro.rb [options]
    --opt1  opt1
    --opt3  opt3

Other options:
    --opt4  opt4
```

Slop version: 4.8.1

**Comment by olleolleolle** [comment]
That does look like unexpected, unintended behaviour. I've labeled it _confirmed_ Bug.

**Comment by leejarvis** [comment]
Good spot!

I thought I might be able to fix this quickly by decrementing the separator index when the previous option specifies `help: false`:

```diff
diff --git a/lib/slop/options.rb b/lib/slop/options.rb
index 9a5f5cc..032e889 100644
--- a/lib/slop/options.rb
+++ b/lib/slop/options.rb
@@ -60,10 +60,16 @@ module Slop
     # Add a separator between options. Used when displaying
     # the help text.
     def separator(string = "")
-      if separators[options.size]
+      index = options.size
+
+      if options.last && !options.last.help? && index != 0
+        index -= 1
+      end
+
+      if separators[index]
         separators[-1] += "\n#{string}"
       else
-        separators[options.size] = string
+        separators[index] = string
       end
     end
 ```

However, there's another bug with separators here:

```ruby
opts = Slop.parse do |o|
  o.boolean "--opt1", "opt1", help: false
  o.boolean "--opt2", "opt2", help: false
  o.separator ""
  o.separator "Other options:"
  o.boolean "--opt3", "opt3", help: false
  o.boolean "--opt4", "opt4"
end
puts opts
```

This code won't print the separators at all, because they're linked to option positions, and we ignore any option with `help: false`, so the separators are overlooked.

Will put some thought into this

**Comment by leejarvis** [comment]
The fix was simpler than that: https://github.com/leejarvis/slop/commit/e5615fbdd7c4cd07e8fb0c1109fc6da56981829f 

Pushing out version 4.8.2 with this change. Thanks for reporting, @ankane

**Comment by ankane** [comment]
Works great, thanks @leejarvis!
