### ISSUE TITLE
Practical example

### ISSUE THREAD

**Issue by nomasprime** [leejarvis/slop#256]
Taking far too long to figure out how to use this from the readme.

A practical real world example would be really helpful.

Particular issue is how to send something like `--file --obviously-not-a-file`.

PS Maybe it's just me.

**Comment by nomasprime** [comment]
Ah, I think `array` might be a good option to deal with this.

Still seemed a lot harder to figure out than it needed to be but not much sleep recently 💀

**Comment by leejarvis** [comment]
As noted on #170, the issue of dealing with unknown flags is not a straightforward resolution. I'm open to discuss options to improve this situation.

> Taking far too long to figure out how to use this from the readme.
> A practical real world example would be really helpful.

The readme includes a few examples. I believe the main example at the top is "real world", but again if you have ideas for improving this I'd love to hear them.

**Comment by nomasprime** [comment]
Hi @leejarvis, apologies, my previous comments were written late at night at the end of a very long tedious day. Didn't mean to sound ungrateful, gem still saved me a lot of time. Thank you.

I hope to revisit this and be more constructive.

**Comment by leejarvis** [comment]
@nomasprime No problem, appreciate the response!

**Comment by leejarvis** [comment]
I'm going to close this for now but I would very much welcome changes to the docs that would help newcomers, so please be candid if you happen to think of something.
