### ISSUE TITLE
CI: Switch away from TravisCI

### ISSUE THREAD

**Issue by olleolleolle** [leejarvis/slop#258]
Example: https://schneems.com/2021/01/13/migrating-a-ruby-library-from-travisci-to-circleci/

TravisCI is shutting down its "free CI build minutes to Open Source projects" initiative.

**Comment by rickhull** [comment]
I don't have time right now to make a PR, but here is how I did it recently:

https://github.com/rickhull/compsci/commit/93ff361dff9ac603bf291a9099351604e28ec410

**Comment by leejarvis** [comment]
I'm not against this but could you add some description of why we want to move to Circle (or move away from Travis, whichever is the motivator)?

**Comment by rickhull** [comment]
Travis got bought by private equity and they reneged on their lifetime support of open source.  Service levels are way down with big delays, and there is a very limited number of "credits" for open source repos.  When you run out, you can beg for more via email.

GH Action is a little more verbose but more powerful in job definition.  Also seems to run much faster than Travis ever did.

**Comment by leejarvis** [comment]
Thanks, @rickhull -- in that case I support this change! If nobody gets to it before me I'll try to take a look soon.

**Comment by leejarvis** [comment]
I sort-of got this working with a [new CI workflow](https://github.com/leejarvis/slop/blob/master/.github/workflows/ci.yml) (based on @rickhull's project). One thing that doesn't seem to work as I expected though is when [a PR](https://github.com/leejarvis/slop/pull/270) has been "fixed" (i.e. is now passing CI), the workflow details disappear entirely, and the "checks" tab seems to show "Waiting for checks information..." indefinitely.

Still, this is better than nothing so I'll leave it as-is for now and revisit once we've processed some PRs.

**Comment by olleolleolle** [comment]
🕺
