### ISSUE TITLE
Some bugs.

### ISSUE THREAD

**Issue by tvw** [leejarvis/slop#262]
Just using the example I found some bugs:

```sh
$ bin/example -l --port
```
Returns 80, the default, which is a bug, because it should return an error because of the missing parameter for ```--port```.

```sh
$ bin/example -l --port xx
```
Returns 80, the default, which is a bug, because it should return an error because the given parameter for ```--port``` is not an integer as it is defined.

Similar bugs exist, when having no defaults defined.

**Comment by SwagDevOps** [comment]
```
vendor/bundle/ruby/2.7.0/gems/slop-4.9.1/lib/slop/types.rb:54: warning: deprecated Object#=~ is called on Integer; it always returns nil
```
