### ISSUE TITLE
Enable frozen strings in Slop using the `# frozen_string_literal: true` pragma

### ISSUE THREAD

**Issue by olleolleolle** [leejarvis/slop#264]
I think we should fix this but we should also enable frozen strings in Slop using the `# frozen_string_literal: true` pragma

_Originally posted by @leejarvis in https://github.com/leejarvis/slop/issues/255#issuecomment-689370633_

**Comment by leejarvis** [comment]
https://github.com/leejarvis/slop/commit/13c2673b4faddd80ebee727703d7d529b07b42de
