### ISSUE TITLE
[question] is there a way to check that one or more of some set of args exist?

### ISSUE THREAD

**Issue by fawaf** [leejarvis/slop#271]
e.g. i have `-i`, `-a`, `-b` args. i want to check that at least one of those 3 args are set to continue. it can be any number of them, but must be at least any one of them.

`blah -i` is valid
`blah -i -a` is valid
`blah -a -b` is valid
`blah -b` is valid
`blah -a -b -i` is valid
etc...

but `blah` is not valid

**Comment by leejarvis** [comment]
You could do something like this:

```ruby
require "slop"

opts = Slop.parse do |o|
  o.on "-i"
  o.on "-a"
  o.on "-b"
end

required_flags = %w(-i -a -b)

if required_flags.none? { |r| opts[r] }
  # none of the flags were present
else
  # proceed
end
```

**Comment by waf-okta** [comment]
ahh, thanks.

**Comment by fawaf** [comment]
ahh thanks
