### ISSUE TITLE
Bool options bug!

### ISSUE THREAD

**Issue by ddnexus** [leejarvis/slop#282]
File "demo.rb"

```ruby
require 'slop'

opts = Slop.parse(validate_types: true) do |o|
  o.bool '-f', '--false', 'False option', default: false
  o.bool '-t', '--true',  'True option',  default: true
end


puts "False option after parsing is: #{opts[:false]}"
puts "True option after parsing is: #{opts[:true]}"
puts
puts 'Set False option to true'
puts 'opts[:false] = true'
opts[:false] = true
puts "False option is now: #{opts[:false]}"
puts
puts 'Set True option to false'
puts 'opts[:true] = false'
opts[:true] = false
puts "True option is now: #{opts[:true]}"
```

```sh
$ ruby demo.rb          
False option after parsing is: false
True option after parsing is: true

Set False option to true
opts[:false] = true
False option is now: true

Set True option to false
opts[:true] = false
True option is now: true
```
The result after the last statement is not exactly what I would expect!!!
Why?

**Comment by ddnexus** [comment]
Definitely a bug: https://github.com/leejarvis/slop/blob/4394168679c2f2900b8419f127dd958aa6b8a0a8/lib/slop/option.rb#L98

That means if a boolean value is `false` it will return the default `value`, which in this case is `true`, hence it is impossible to get the right (`false`) value!

**Comment by ddnexus** [comment]
Is this project abandonware?

I switched to [Optimist](https://github.com/ManageIQ/optimist)... single-file lib drop-in that doesn't need to be a gem dependency.

**Comment by leejarvis** [comment]
Thanks for the report. 

> Is this project abandonware?

No it is still maintained.

> I switched to [Optimist](https://github.com/ManageIQ/optimist)... single-file lib drop-in that doesn't need to be a gem dependency.

Great, I'm glad you found a solution.

**Comment by ddnexus** [comment]
> Great, I'm glad you found a solution.

I needed to release [pagy](https://github.com/ddnexus/pagy), and I fricked out, but I like your project! 👍

**Comment by leejarvis** [comment]
@ddnexus What's the purpose you're forcibly changing the value in the Hash? e.g. doing this: `opts[:false] = true` — this is unexpected behaviour IMO. Maybe Slop should raise an error when you try to reassign a value, but it's meant to be readonly. If you change the value explicitly then we no longer have tracking of the original value. The following all works as expected:

```
% ruby demo.rb
{:false=>false, :true=>true}
% ruby demo.rb --false
{:false=>true, :true=>true}
% ruby demo.rb --false --no-true
{:false=>true, :true=>false}
```

**Comment by ddnexus** [comment]
Well, an accessor method that doesn't return the actual instance variable value, but changes it on the fly because it "expects" it to be any arbitrary non-false value, is conceptually plain wrong IMO.

You could object that it's not an accessor, but a method that returns the content of an instance variable is hardly something else... even if it perform tricks on your back 😉.

Returning a default value on read instead of assigning it to the instance variable on creation is also not exactly following the principle of less surprise.... at least my own surprise 🫢.

But that's kinda personal.

> Maybe Slop should raise an error when you try to reassign a value, but it's meant to be readonly

Why would you want to impose your own concept of "options" to your users? If I want to freeze the options I can just do it. If I want to use slop as a simple initializer/validator of some options, why would you want to stop me to edit the original options based on other conditional logic later in the script? Wouldn't that just reduce the flexibility of your tool for no advantage?

> If you change the value explicitly then we no longer have tracking of the original value.

I definitely miss the point of "tracking" the original value.

My ideal options parser should just give me a simple hash of options after defaults and validations and leave the rest to me.

**Comment by leejarvis** [comment]
> My ideal options parser should just give me a simple hash of options after defaults and validations and leave the rest to me

Sure. This is what `to_h` is for. `opts` is a `Slop::Result` and shouldn't be treated like a Hash, despite the existence of a `#[]` method.

**Comment by ddnexus** [comment]
So you should definitely raise an error if the user tries to change the `Slop::Result`, and put the `opts.to_hash` as a suggestion in the error message itself, in order to educate the user that indeed may think that opts IS a Hash.

Principle of less surprise! :smile:
